[package]
name = "bitfix"
version = "0.1.1-pre.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
strip = true
lto = true

[dependencies]
anyhow = "1.0.100"
once_cell = { version = "1.21.3", features = ["std"] }
patternsleuth_scanner = { git = "https://github.com/trumank/patternsleuth", rev = "9518131" }
proxy_dll = { git = "https://github.com/trumank/proxy_dll.git", rev = "a0c0772" }
rlua = "0.19.8"
simple-log = "1.9.0"
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_System_SystemServices",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_LibraryLoader",
  "Win32_System_Memory",
  "Win32_System_Threading",
  "Win32_Security",
  "Win32_System_ProcessStatus",
] }
